from pathlib import Path
from time import time_ns

from PIL import Image
from PIL.PngImagePlugin import PngInfo

from source.py.image_model import ImageModel

AI_GEN_XMP_PACKET = """<?xpacket begin="\ufeff" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
   xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/">
   <Iptc4xmpExt:DigitalSourceType>http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia</Iptc4xmpExt:DigitalSourceType>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>"""
"""XMP packet marking an image as AI-generated."""


class OutputImage:
    """An image generated by ZPix, on its way to the output folder."""

    def __init__(
        self,
        instance: Image.Image,
        output_dir: Path,
        lora_name: str | None = None,
    ):
        """Initialize an output image, not yet written to disk.

        Args:
            instance: Generated image.
            output_dir: The folder where generated images are saved.
            lora_name: Name of any LoRA used (e.g. "Retro_Anime").
        """
        self.instance = instance

        self.metadata = PngInfo()
        self.metadata.add_itxt("XML:com.adobe.xmp", AI_GEN_XMP_PACKET)

        # Milliseconds precision is enough to avoid filename collision.
        self.id = str(time_ns() // 1_000_000)

        parent_dir = output_dir / lora_name if lora_name else output_dir
        self.path = parent_dir / f"image_{self.id}.png"

    def embed_settings(
        self,
        model: ImageModel,
        prompt: str,
        seed: int,
        steps: int,
        cfg: float,
    ) -> None:
        """Embed generation settings of this image in PNG text chunks."""
        self.metadata.add_text("model", model.id)
        self.metadata.add_itxt("prompt", prompt)
        self.metadata.add_text("seed", str(seed))
        self.metadata.add_text("steps", str(steps))
        self.metadata.add_text("cfg", str(cfg))

    def save(self) -> None:
        """Write this image to the output folder."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.instance.save(self.path, pnginfo=self.metadata)
